Router.route('/', {name: 'Home'});
Router.route('/add-info', {name: 'addInfo'});
Router.route('/today-index', {name: 'todayIndex'});
Router.route('/ten-day', {name: 'tenDay'});
Router.route('/fish-1', {name: 'fish1'});
Router.route('/fish-2', {name: 'fish2'});
Router.route('/fish-3', {name: 'fish3'});
Router.route('/fish-4', {name: 'fish4'});
Router.route('/fish-5', {name: 'fish5'});